### ISSUE TITLE
Pass Click Values to Python

### ISSUE THREAD

**Issue by ryanallen82** [ChrisChross/streamlit-agraph#12]
I'm not sure if this is currently possible, but it would be great if there was a way to pass the click value (i.e. Clicked on node {value}) back to Streamlit/Python to save as a variable or filter a dataframe. For example if I clicked on Node 1 it would be able to pass Node 1 back so I could use it to filter a dateframe to only show rows containing Node 1.

**Comment by ChrisChross** [comment]
Hey @ryanallen82 ,

good idea, i'd like to have it too.
I will think about it and let know if it is possible!

**Comment by zjorgensenbits** [comment]
agree, would be super useful!

**Comment by zjorgensenbits** [comment]
I figured out how to do this. Just edit streamlit_agraph/frontend/src//AgraphComponent.tsx and add `Streamlit.setComponentValue(nodeId);` to the click handlers, in place, or in addition to, the alert window. Then, in your Python code, the agraph widget's value will evaluate to the clicked ID.
Make sure you rebuild and reinstall the module after you make the modification:
 ```
cd streamlit_agraph/frontend
npm install
npm run build
cd ../..
pip install -U -e streamlit-agraph 
```

**Comment by ryanallen82** [comment]
Sweet! Good work and thank you!

**Comment by ChrisChross** [comment]
Tanks for the pull request @zjorgensenbits. Could you please provide an example how to use that in python code?
