### ISSUE TITLE
How to set layout?

### ISSUE THREAD

**Issue by fabiogra** [ChrisChross/streamlit-agraph#15]
Is it possible to set layout to display nodes and edges using a specific layout/algorithm?

It could be useful draw a directed tree graph, for example to show pipelines.

**Comment by ChrisChross** [comment]
Hey @fabiogra,

good question. I had a similar question before. So far, there is no function for it. 
However, I agree that it would be nice to have it! Are you interested in making a function for it? 

This is how it could go: 
1) Set staticGraph=True or staticGraphWithDragAndDrop=True, (in the config).
2) define some hierachies and based on that: 
3) Add cords (x, y) to each node.

Best regards 
Chris

**Comment by ChrisChross** [comment]
well done.
