### ISSUE TITLE
Release a new version on PyPi?

### ISSUE THREAD

**Issue by marcopalmeri** [ChrisChross/streamlit-agraph#21]
Hi @ChrisChross,

I am trying to use the new feature you added [here](https://github.com/ChrisChross/streamlit-agraph/pull/18).  However, it seems the last pypi release predates that change.

Do you have any plans to push a new release to pypi?

Thanks!
Marco

**Comment by arkanoid87** [comment]
not yet on pypi

**Comment by ChrisChross** [comment]
Done, sorry for the delay.
