### ISSUE TITLE
How to customize Node label?

### ISSUE THREAD

**Issue by pp2moonbird** [ChrisChross/streamlit-agraph#7]
Currently this is the way to initialize a Node
``` python
class Node:
  def __init__(self,
              id,
              size=250,
              color="#ACDBC9",
              renderLabel=True,
              labelPosition="right",
              svg="",
              symbolType="circle",
              strokeColor="" #F7A7A6
               ):
```

Is there any way to specify node label? I wish I could assign a different value than node_id to label and then display the label in the graph.

**Comment by ChrisChross** [comment]
Hi @pp2moonbird,

thanks for your request. 
I gave it quick try. According to their doc:
https://danielcaldas.github.io/react-d3-graph/docs/index.html
there should be a label or labelProperty.  
Maybe you can try to add and let me know if it worked?

**Comment by ChrisChross** [comment]
Ok so I have uploaded a new version to pypi. In this version you can just add propeties you found in the doc as arguments. 
(using kwargs).

**Comment by pp2moonbird** [comment]
@ChrisChross Thanks for your prompt action and reply.

I downloaded latest pypi and modified my code. It works like charm

Share my sample code in case anyone ask same question:

Key point is add `node.labelProperty` in the config object according to the [doc](https://danielcaldas.github.io/react-d3-graph/docs/index.html#node-label-property) 

```python
nodes = [Node(id=n['id'], label=n['name']) for n in json_nodes] # add value to payload
edges = [Edge(source= e['sourceId'], target=e['targetId']) for e in json_edges]

config = Config(width=1600, 
                height=1000, 
                directed=True,
                nodeHighlightBehavior=True, 
                highlightColor="#F7A7A6", # or "blue"
                collapsible=True,
                node={'labelProperty':'label'} 
                ) 

return_value = agraph(nodes=nodes, 
                      edges=edges, 
                      config=config)
```

**Comment by ChrisChross** [comment]
Awesome, thank you!

**Comment by ChrisChross** [comment]
@pp2moonbird do you think there is away to display a label for a link like this too?

**Comment by ChrisChross** [comment]
Nvm. Found the solution. It is very similar, however, one more attribute is needed: 
link={'labelProperty': 'label', 'renderLabel': True}
