### ISSUE TITLE
Update example code on Pypi.org

### ISSUE THREAD

**Issue by Roman-kazi** [ChrisChross/streamlit-agraph#9]
The example code posted ( here: https://pypi.org/project/streamlit-streamlit-agraph/ ) seems to be broken or inadequate. Please update it.

**Comment by ChrisChross** [comment]
My applogies for the wrong upload. Can you please try to use: https://pypi.org/project/streamlit-agraph/ ?

**Comment by Roman-kazi** [comment]
Okay great, I am closing this issue.
